### PR TITLE
Packages updated and vulnerabilities fixed

### PR DESCRIPTION
**Pull request by Jazper**
Result:
image

It seems all scripts works as before.

### CODE REVIEW

**Comment by th0r** [comment]
Did you try to build it? Does built version work ok?

**Comment by Jazper** [comment]
> Did you try to build it? Does built version work ok?

Yes. It builds without errors.
image

**Comment by th0r** [comment]
I mean did you try opening it in the browser? Does it look ok?

**Comment by Jazper** [comment]
> I mean did you try opening it in the browser? Does it look ok?

I can only run serve. And yes, it opens application. 
image

Is it supposed to look like this? Content is just a picture :)

**Comment by th0r** [comment]
Yep, that's ok. LGTM 👍

**Pull request merged**
